### ISSUE TITLE
the binary_crossentropy test is failing

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#1069]
Running the binary cross entropy test triggers an assertion failure.
```
 python3 ./tests/unit/python/execution_tree/binary_crossentropy.py
```
Possibly, this is actually an HPX issue instead of a Phylanx issue.
```
{file}: /hpx/hpx/runtime/threads/detail/scheduling_loop.hpp
{line}: 610
{function}: void hpx::threads::detail::scheduling_loop(std::size_t, SchedulingPolicy&, hpx::threads::detail::scheduling_counters&, hpx::threads::detail::scheduling_callbacks&) [with SchedulingPolicy = hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>; std::size_t = long unsigned int]
{what}: Assertion 'thrd->get_scheduler_base() == &scheduler' failed: HPX(assertion_failure)
```
Note that this is a debug build.

Stack trace:
```
#0  0x00007f2fc4cf67ae in abort () from /lib64/libc.so.6
#1  0x00007f2fbdaf1fc4 in hpx::detail::assertion_handler (loc=..., expr=0x7f2fbe6b62e0 "thrd->get_scheduler_base() == &scheduler",
    msg="") at /hpx/src/runtime_handlers.cpp:46
#2  0x00007f2fbe451b3f in hpx::assertion::detail::handle_assert (loc=...,
    expr=0x7f2fbe6b62e0 "thrd->get_scheduler_base() == &scheduler", msg="") at /hpx/libs/assertion/src/assertion.cpp:47
#3  0x00007f2fbe05ed96 in hpx::assertion::detail::evaluate_assert<hpx::threads::detail::scheduling_loop<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >(unsigned long, hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>&, hpx::threads::detail::scheduling_counters&, hpx::threads::detail::scheduling_callbacks&)::{lambda()#1}, hpx::threads::detail::scheduling_loop<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >(unsigned long, hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>&, hpx::threads::detail::scheduling_counters&, hpx::threads::detail::scheduling_callbacks&)::{lambda()#2}>(hpx::threads::detail::scheduling_loop<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >(unsigned long, hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>&, hpx::threads::detail::scheduling_counters&, hpx::threads::detail::scheduling_callbacks&)::{lambda()#1} const&, hpx::assertion::source_location const&, char const*, hpx::threads::detail::scheduling_loop<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >(unsigned long, hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo>&, hpx::threads::detail::scheduling_counters&, hpx::threads::detail::scheduling_callbacks&)::{lambda()#2} const&) (msg=...,
    expr_string=0x7f2fbe6b62e0 "thrd->get_scheduler_base() == &scheduler", loc=..., expr=...)
    at /hpx/libs/assertion/include/hpx/assertion/evaluate_assert.hpp:28
#4  hpx::threads::detail::scheduling_loop<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> > (num_thread=0, scheduler=..., counters=...,
    params=...) at /hpx/hpx/runtime/threads/detail/scheduling_loop.hpp:610
#5  0x00007f2fbe0205db in hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::thread_func (
    this=0x484bcd0, thread_num=0, global_thread_num=0, startup=std::shared_ptr<hpx::util::barrier> (use count 1, weak count 0) = {...})
    at /hpx/hpx/runtime/threads/detail/scheduled_thread_pool_impl.hpp:507
#6  0x00007f2fbe0c250d in std::__invoke_impl<void, void (hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priori--Type <RET> for more, q to quit, c to continue without paging--
ty_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::*)(unsigned long, unsigned long, std::shared_ptr<hpx::util::barrier>), hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >*, unsigned long, unsigned long, std::shared_ptr<hpx::util::barrier> > (__f=
    @0x4841410: (void (hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::*)(hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> > * const, unsigned long, unsigned long, std::shared_ptr<hpx::util::barrier>)) 0x7f2fbe01fc72 <hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::thread_func(unsigned long, unsigned long, std::shared_ptr<hpx::util::barrier>)>, __t=@0x4841408: 0x484bcd0, __args#0=@0x4841400: 0,
    __args#1=@0x48413f8: 0, __args#2=...) at /usr/include/c++/9/bits/invoke.h:73
#7  0x00007f2fbe0c189f in std::__invoke<void (hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::*)(unsigned long, unsigned long, std::shared_ptr<hpx::util::barrier>), hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >*, unsigned long, unsigned long, std::shared_ptr<hpx::util::barrier> > (__fn=
    @0x4841410: (void (hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::*)(hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> > * const, unsigned long, unsigned long, std::shared_ptr<hpx::util::barrier>)) 0x7f2fbe01fc72 <hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::thread_func(unsigned long, unsigned long, std::shared_ptr<hpx::util::barrier>)>, __args#0=@0x4841408: 0x484bcd0, __args#1=@0x4841400: 0,
    __args#2=@0x48413f8: 0, __args#3=...) at /usr/include/c++/9/bits/invoke.h:95
#8  0x00007f2fbe0c0f43 in std::thread::_Invoker<std::tuple<void (hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::*)(unsigned long, unsigned long, std::shared_ptr<hpx::util::barrier>), hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >*, unsigned long, unsigned long, std::shared_ptr<hpx::util::barrier> > >::_M_invoke<0ul, 1ul, 2ul, 3ul, 4ul> (this=0x48413e8) at /usr/include/c++/9/thread:244
#9  0x00007f2fbe0c0626 in std::thread::_Invoker<std::tuple<void (hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::loca--Type <RET> for more, q to quit, c to continue without paging--
l_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::*)(unsigned long, unsigned long, std::shared_ptr<hpx::util::barrier>), hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >*, unsigned long, unsigned long, std::shared_ptr<hpx::util::barrier> > >::operator() (
    this=0x48413e8) at /usr/include/c++/9/thread:251
#10 0x00007f2fbe0bffac in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >::*)(unsigned long, unsigned long, std::shared_ptr<hpx::util::barrier>), hpx::threads::detail::scheduled_thread_pool<hpx::threads::policies::local_priority_queue_scheduler<std::mutex, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_fifo, hpx::threads::policies::lockfree_lifo> >*, unsigned long, unsigned long, std::shared_ptr<hpx::util::barrier> > > >::_M_run (this=0x48413e0) at /usr/include/c++/9/thread:195
#11 0x00007f2fbc8626f4 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#12 0x00007f2fc4ff54e2 in start_thread () from /lib64/libpthread.so.0
#13 0x00007f2fc4dd2643 in clone () from /lib64/libc.so.6
```

**Comment by stevenrbrandt** [comment]
Actually, it seems this is being triggered by much simpler Phylanx code...
```
from phylanx import Phylanx, PhylanxSession
from phylanx.util import phyhelp

PhylanxSession.init(1)
```

**Comment by stevenrbrandt** [comment]
Nevermind. Configuration issue.
