### ISSUE TITLE
No arg lambda's don't work

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#1104]
```
from phylanx import Phylanx

@Phylanx
def foo():
    f = lambda : print("Hello")

foo()
```
creates
```
--------------------------------------------------------------------------
[[38797,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: 29dd8de5e0ff

Another transport will be used instead, although this may result in
lower performance.
--------------------------------------------------------------------------
PAPI lmsensors component found...
PAPI RAPL component found...
No RAPL events found.
Can't open fd for cpu0: Permission denied.
Traceback (most recent call last):
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 374, in _compile_or_load
    physl_db = db(_name_of_importing_file)
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl_db.py", line 95, in __init__
    self.dbname, self.db, created = self.ensure_db(name, version)
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl_db.py", line 34, in ensure_db
    os.makedirs(dbdir)
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/__physlcache__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "x0.py", line 7, in <module>
    foo()
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/transducer.py", line 162, in __call__
    result = self.backend.call(*mapped_args, **mapped_kwargs)
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 548, in call
    self._ensure_global_state()
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 421, in _ensure_global_state
    PhySLFunction.compile()
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 348, in compile
    func.compile_function()
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 342, in compile_function
    self.physl._ensure_is_compiled()
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 434, in _ensure_is_compiled
    self._compile_or_load()
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 400, in _compile_or_load
    self.__ast__ = phylanx.ast.generate_ast(self.__src__)
RuntimeError: Error! Expecting ")" line 1:
define$4$0(foo$4$0, lambda$4$0(define$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Error! Expecting ")" line 1:
define$4$0(foo$4$0, lambda$4$0(define$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Error! Expecting ")" line 1:
define$4$0(foo$4$0, lambda$4$0(define$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Error! Expecting ")" line 1:
define$4$0(foo$4$0, lambda$4$0(define$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
~~~~~~~~~~~~~~~~~~^
Error! Incomplete parse: line 1:
define$4$0(foo$4$0, lambda$4$0(define$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
^
```

**Comment by stevenrbrandt** [comment]
Note that if I add an arg, it works...
```
from phylanx import Phylanx

@Phylanx
def foo():
    f = lambda a : print("Hello")

foo()
```

**Comment by stevenrbrandt** [comment]
Note there is a second error present in the above execution related to finding the __phsylcache__. The workaround for this is to call the python function by absolute path. The primary error above still happens.
```
$ python3 $PWD/u.py
--------------------------------------------------------------------------
[[45207,1],0]: A high-performance Open MPI point-to-point messaging module
was unable to find any relevant network interfaces:

Module: OpenFabrics (openib)
  Host: 29dd8de5e0ff

Another transport will be used instead, although this may result in
lower performance.
--------------------------------------------------------------------------
PAPI lmsensors component found...
PAPI RAPL component found...
No RAPL events found.
Can't open fd for cpu0: Permission denied.
Traceback (most recent call last):
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 386, in _compile_or_load
    self.__ast__ = phylanx.ast.generate_ast(self.__src__)
RuntimeError: Error! Expecting ")" line 1:
define$4$0(foo$4$0, lambda$4$0(define$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Error! Expecting ")" line 1:
define$4$0(foo$4$0, lambda$4$0(define$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Error! Expecting ")" line 1:
define$4$0(foo$4$0, lambda$4$0(define$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Error! Expecting ")" line 1:
define$4$0(foo$4$0, lambda$4$0(define$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
~~~~~~~~~~~~~~~~~~^
Error! Incomplete parse: line 1:
define$4$0(foo$4$0, lambda$4$0(define$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
^
: HPX(bad_parameter)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jovyan/phylanx/u.py", line 7, in <module>
    foo()
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/transducer.py", line 162, in __call__
    result = self.backend.call(*mapped_args, **mapped_kwargs)
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 548, in call
    self._ensure_global_state()
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 421, in _ensure_global_state
    PhySLFunction.compile()
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 348, in compile
    func.compile_function()
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 342, in compile_function
    self.physl._ensure_is_compiled()
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 434, in _ensure_is_compiled
    self._compile_or_load()
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 400, in _compile_or_load
    self.__ast__ = phylanx.ast.generate_ast(self.__src__)
RuntimeError: Error! Expecting ")" line 1:
define$4$0(foo$4$0, lambda$4$0(store$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Error! Expecting ")" line 1:
define$4$0(foo$4$0, lambda$4$0(store$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Error! Expecting ")" line 1:
define$4$0(foo$4$0, lambda$4$0(store$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
Error! Expecting ")" line 1:
define$4$0(foo$4$0, lambda$4$0(store$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
~~~~~~~~~~~~~~~~~~^
Error! Incomplete parse: line 1:
define$4$0(foo$4$0, lambda$4$0(store$5$4(f$5$4, lambda$5$8(, cout$5$17("Hello")))))
^
: HPX(bad_parameter)
```

**Comment by hkaiser** [comment]
The first error is most probably caused by the exception being thrown and should go away once the second error is fixed.

The second error is caused by a bad PhySL code gen that causes a ',' to be generated even if it should generate one. @rtohid any idea what's causing this?
