### ISSUE TITLE
inaccessible variable

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#1198]
The python code
```
from phylanx import Phylanx
import numpy as np

@Phylanx(debug=True)
def foo2(ztot):
    t = 3
    ztot[t] -= 1.0

ztot = np.zeros((10,))
foo2(ztot)
```
generates the PhySL code
```
define(
    foo2,
    ztot,
    block(
        define(t, 3),
        store(
            slice(ztot, t),
            __sub(
                slice(ztot, t),
                1.0
            )
        )
    )
)
```
and fails with the error message
```
Traceback (most recent call last):
  File "bug.py", line 10, in <module>
    foo2(ztot)
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/transducer.py", line 168, in __call__
    result = self.backend.call(*mapped_args, **mapped_kwargs)
  File "/home/jovyan/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 578, in call
    self.wrapped_function.__name__, *args, **kwargs)
RuntimeError: bug.py(7, 9): access-variable$t:: the variable 't' is unbound in the current execution environment: HPX(bad_parameter)
```
which is clearly incorrect as t is bound to 3.

**Comment by hkaiser** [comment]
@stevenrbrandt Uhh, that's really strange, I'll have a look.
