### ISSUE TITLE
list(1) does not match itself

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#1242]
```
import numpy as np

@Phylanx
def foo():
    if list(1) == list(1):
        print("list(1) matches itself")
    else:
        print("list(1) does not match itself")

foo()
```
prints
```
print("list(1) does not match itself")
```

**Comment by hkaiser** [comment]
FWIW, for me this code throws an exception printing:
```
Traceback (most recent call last):
  File "D:\Devel\phylanx\tests\regressions\python\1242_list_comparison.py", line 16, in <module>
    result = foo()
  File "D:\Devel\phylanx\build\All.v16.vcpkg\python\build\lib.win-amd64-3.6\phylanx\ast\transducer.py", line 168, in __call__
    result = self.backend.call(*mapped_args, **mapped_kwargs)
  File "D:\Devel\phylanx\build\All.v16.vcpkg\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 579, in call self.wrapped_function.__name__, *args, **kwargs)
RuntimeError: D:\Devel\phylanx\tests\regressions\python\1242_list_comparison.py(13, 11): __eq:: left hand side and right hand side are incompatible and can't be compared: HPX(bad_parameter)
```
I will implement the missing comparison operation on lists.
