### ISSUE TITLE
Passing a dict to Phylanx is not possible

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/phylanx#1255]
```
from phylanx import Phylanx


dict_nn = {
    "Patrick " : "Cool"
    }

@Phylanx(debug=True)
def change(data):
    data["Patrick"] = "Mega cool"
    
    
if __name__ == "__main__":
    
    change(dict_nn)
```

running this code without the decorator works. Running this code with the decorator results in 
```

diehlpk@localhost ~/g/SOO (phylanx_share)> python example.py
Traceback (most recent call last):
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 383, in _compile_or_load
    self.ir = self._apply_rule(self.python_tree.body[0])
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 1028, in _FunctionDef
    body = self._block(node.body)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 952, in _block
    block = tuple(map(self._apply_rule, node))
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 684, in _Assign
    symbol = self._apply_rule(node.targets[0])
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 1294, in _Subscript
    slice_ = self._apply_rule(node.slice)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 1090, in _Index
    return self._apply_rule(node.value)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 919, in _Constant
    return self._apply_rule(node.value)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "<string>", line 1, in <module>
AttributeError: 'PhySL' object has no attribute '_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example.py", line 15, in <module>
    change(dict_nn)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/transducer.py", line 168, in __call__
    result = self.backend.call(*mapped_args, **mapped_kwargs)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 566, in call
    self._ensure_global_state()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 435, in _ensure_global_state
    PhySLFunction.compile()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 348, in compile
    func.compile_function()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 342, in compile_function
    self.physl._ensure_is_compiled()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 448, in _ensure_is_compiled
    self._compile_or_load()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 405, in _compile_or_load
    self.ir = self._apply_rule(self.python_tree.body[0])
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 1028, in _FunctionDef
    body = self._block(node.body)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 952, in _block
    block = tuple(map(self._apply_rule, node))
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 684, in _Assign
    symbol = self._apply_rule(node.targets[0])
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 1294, in _Subscript
    slice_ = self._apply_rule(node.slice)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 1090, in _Index
    return self._apply_rule(node.value)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 919, in _Constant
    return self._apply_rule(node.value)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 528, in _apply_rule
    return eval('self._%s' % node_name)(node)
  File "<string>", line 1, in <module>
AttributeError: 'PhySL' object has no attribute '_str'
FATAL: exception not rethrown
```

**Comment by hkaiser** [comment]
@rtohid could you have a look at this, please? This seems to be a frontend issue.

**Comment by hkaiser** [comment]
Please note also that this is Python 3.8. There has been some changes how literal values are represented in the AST. @diehlpk was already complaining about a similar issue involving a missing `_float` attribute yesterday, which apparently is caused by similar changes.

**Comment by rtohid** [comment]
@diehlpk thanks for using Phylanx. In the absence of the decorator, code works as expected- if there is no decorator, code is run through the Python interpreter and the exact same behavior (as Python) is expected. 

For the error, please see:
https://github.com/STEllAR-GROUP/phylanx/blob/bda8c0dabe91e89a81c53c7da4ae92b9147870b3/python/phylanx/ast/physl.py#L919
if the `node.value` is a literal you should return it instead of calling `_apply_rule` method. Please see [constant](https://greentreesnakes.readthedocs.io/en/latest/nodes.html#Constant) for more info.

I am not aware of the state of dictionary support in Phylanx at this point, @stevenrbrandt did you have a fix or similar issues? I remember you're dealing with dictionaries recently.

**Comment by hkaiser** [comment]
@rtohid I don't think @diehlpk has changed the Phylanx code in any way. Would you be able to make the changes you suggested? Also, I don't think this is related to the existence/missing of dictionary support in Phylanx itself is something relevant here, we first need to make the PhySL being generated properly.

**Comment by diehlpk** [comment]
@rtohid I did not change anything in Phylanx. I just will report bugs and missing primitives for the SSO project.

**Comment by diehlpk** [comment]
@rtohid I can confirm that we have this bug for any data type.

**Comment by rtohid** [comment]
@diehlpk sorry, I misunderstood. I thought you're interested in becoming a contributer.

Yes, that's expected, the above suggestion should fix this too. Unfortunately, right now bug fixes for the old frontend is not our priority as the new one is getting integrated in [JetLag](https://github.com/STEllAR-GROUP/JetLag.git). If it is something urgent, please let me know I'll try to fix it over the weekend.

**Comment by diehlpk** [comment]
@rtohid Nan and I can use the new frontend if things will work there. If not we would prefer, if you could fix the old one, so we can use Phylanx within the SSO project. I will do whatever is easier.

**Comment by rtohid** [comment]
Sure, I let you know when it's in production.

**Comment by hkaiser** [comment]
Please see #1257 for a possible fix
