### ISSUE TITLE
np.random.rand does not work

### ISSUE THREAD

**Issue by diehlpk** [STEllAR-GROUP/phylanx#1258]
```
from phylanx import Phylanx
import numpy as np

dict_nn = {
    "Patrick" : "Cool"
    }

@Phylanx(debug=True)
def change():
    np.random.randn(10)

    
    
if __name__ == "__main__":
    
    change()
```

results in 

```
diehlpk@localhost ~/g/SOO (phylanx_share_dict)> python example.py
define(
    change,
    lambda(
        randn(10)
    )
)
Traceback (most recent call last):
  File "example.py", line 16, in <module>
    change()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/transducer.py", line 168, in __call__
    result = self.backend.call(*mapped_args, **mapped_kwargs)
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 566, in call
    self._ensure_global_state()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 435, in _ensure_global_state
    PhySLFunction.compile()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 348, in compile
    func.compile_function()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 342, in compile_function
    self.physl._ensure_is_compiled()
  File "/home/diehlpk/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 451, in _ensure_is_compiled
    phylanx.execution_tree.compile(
RuntimeError: example.py(10, 4): couldn't find function 'randn' in symbol table: HPX(bad_parameter)
FATAL: exception not rethrown
```

**Comment by taless474** [comment]
`random` interface is not exactly like NumPy's. I tested this and it worked:
```py
from phylanx import Phylanx
import numpy as np


@Phylanx(debug=True)
def change(sz):
    return np.random(sz)
	
change(10)
```
Please note that the default option in using a normal distribution. To pass the distribution you can try something like the following:
```py
from phylanx import Phylanx
import numpy as np


@Phylanx(debug=True)
def change(sz):
    return np.random(sz,["uniform_int", -3, 2])
	
print(change([3,4]))
```
```console
define(
    change,
    sz,
    random(
        sz,
        list(
            "uniform_int",
            __minus(3),
            2
        )
    )
)
[[ 1. -1.  2.  2.]
 [-3.  0.  1.  0.]
 [-3. -1. -2. -2.]]
```
The result is a 3x4 matrix filled with elements in the range of (-3,2) from the uniform_int distribution.

**Comment by diehlpk** [comment]
cc #1261

**Comment by diehlpk** [comment]
I think that we should try to add the full `np.random` interface, since this is widely used in ML applications.

**Comment by diehlpk** [comment]
I think having the simple random functions and the two permutations here [0] would be beneficial. One can implement most of them using random.random pr np.random, however, for users it would be easier to support them in the near future. 


[0] https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html
