### ISSUE TITLE
Validation issue in nightly tests

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/phylanx#1272]
Two of the AST tests are failing (probably the whitespace):

```
231/265 Test #348: tests.unit.python.ast.generate_ast ...............................................***Failed    1.02 sec
(A$1$1 + B$1$5)
A$1$1
B$1$5
+
 (A$1$1 + B$1$5)
A$1$1
B$1$5
optoken.op_plus
Traceback (most recent call last):
  File "/var/lib/buildbot/workers/phylanx/x86_64-gcc7-release/build/tests/unit/python/ast/generate_ast.py", line 74, in <module>
    '\n')
  File "/var/lib/buildbot/workers/phylanx/x86_64-gcc7-release/build/tests/unit/python/ast/generate_ast.py", line 43, in test_expression
    assert (visitor.result == expected)
AssertionError
```
```
234/265 Test #351: tests.unit.python.ast.traverse_ast ...............................................***Failed    0.98 sec
(A$1$1 + B$1$5)
A$1$1
B$1$5
+
 (A$1$1 + B$1$5)
A$1$1
B$1$5
optoken.op_plus
Traceback (most recent call last):
  File "/var/lib/buildbot/workers/phylanx/x86_64-gcc7-release/build/tests/unit/python/ast/traverse_ast.py", line 43, in <module>
    test_traverse('A + B', '(A$1$1 + B$1$5)\nA$1$1\nB$1$5\noptoken.op_plus\n')
  File "/var/lib/buildbot/workers/phylanx/x86_64-gcc7-release/build/tests/unit/python/ast/traverse_ast.py", line 36, in test_traverse
    assert (visitor.generated_string == expected)
AssertionError
```

**Comment by hkaiser** [comment]
Will fix, thanks!

**Comment by khuck** [comment]
looks fixed, thanks!
