### ISSUE TITLE
Problem creating an hstack

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#1280]
For this code:
```
from phylanx import Phylanx
import numpy as np

@Phylanx
def zip():
    a = hstack([[1,2],[3,4]])
    print(diag(a)) # works
    print(diag(hstack([[1,2],[3,4]]))) # does not work

zip()
````

Output
```
Singularity> python3 y.py
[1, 4]
Traceback (most recent call last):
  File "y.py", line 10, in <module>
    zip()
  File "/usr/local/userbase/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/transducer.py", line 191, in __call__
    result = self.backend.call(*mapped_args, **mapped_kwargs)
  File "/usr/local/userbase/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 588, in call
    self.wrapped_function.__name__, *args, **kwargs)
RuntimeError: y.py(8, 10): diag:: primitive_argument_type does not hold a numeric value type (type held: 'phylanx::ir::range'): HPX(bad_parameter)
```

**Comment by hkaiser** [comment]
Nice catch!

**Comment by hkaiser** [comment]
This is caused by a problem in the frontend. Here is the generated PhySL code:
```
define(
    zip,
    lambda(
        block(
            define(
                a,
                vstack(
                    list(
                        hstack(
                            list(1, 2)
                        ),
                        hstack(
                            list(3, 4)
                        )
                    )
                )
            ),
            diag(a),
            diag(
                list(
                    vstack(
                        list(
                            hstack(
                                list(1, 2)
                            ),
                            hstack(
                                list(3, 4)
                            )
                        )
                    )
                )
            )
        )
    )
)
```
as you can see, the `hstack()` used in a variable definition generates correct PhySL code, while using it in a function call wraps it with an additional `list()`.

@rtohid would you have the time to have a look, please?

**Comment by hkaiser** [comment]
@rtohid I think I have it under control, thanks (see #1286).
