### ISSUE TITLE
Error processing if statement

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#1301]
```
from phylanx import Phylanx
import numpy as np


@Phylanx(debug=True)
def lshape(x):
    if ((__type(x) == __type(list())) and (len(x)==0)):
        return (0,)
    else:
        return np.shape(x)


lshape(np.linspace(0,1,100))
```
Produces
```
Traceback (most recent call last):
  File "x.py", line 13, in <module>
    lshape(np.linspace(0,1,100))
  File "/home/jovyan/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/transducer.py", line 191, in __call__
    result = self.backend.call(*mapped_args, **mapped_kwargs)
  File "/home/jovyan/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 586, in call
    self._ensure_global_state()
  File "/home/jovyan/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 447, in _ensure_global_state
    PhySLFunction.compile()
  File "/home/jovyan/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 349, in compile
    func.compile_function()
  File "/home/jovyan/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 343, in compile_function
    self.physl._ensure_is_compiled()
  File "/home/jovyan/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 463, in _ensure_is_compiled
    phylanx.execution_tree.compile(
RuntimeError: x.py(7, 4): attempt to call function 'if' with too many arguments (expected: 2, supplied: 4): HPX(bad_parameter)
```

**Comment by stevenrbrandt** [comment]
Note that it works with this trivial modification...
```
from phylanx import Phylanx
import numpy as np


@Phylanx(debug=True)
def lshape(x):
    zero = (0,)
    if ((__type(x) == __type(list())) and (len(x)==0)):
        return zero
    else:
        return np.shape(x)


lshape(np.linspace(0,1,100))
```

**Comment by hkaiser** [comment]
Thanks @stevenrbrandt, this is so wrong on multiple levels... even the error message is incorrect :/
