### ISSUE TITLE
Can't mutate data structures

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#1317]
The following code
```
from phylanx import Phylanx

@Phylanx
def foo():
    a={"groups":1,"fish":2}
    b={"LEFT":a, "RIGHT":[3,4]}
    b["LEFT"]["groups"]=None

foo()
```
Throws this exception
```
Traceback (most recent call last):
  File "x.py", line 18, in <module>
    foo()
  File "/home/jovyan/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/transducer.py", line 191, in __call__
    result = self.backend.call(*mapped_args, **mapped_kwargs)
  File "/home/jovyan/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 598, in call
    result = phylanx.execution_tree.eval(
RuntimeError:
<stack frames>
  [1]: x.py: foo2:: (Python)
  [2]: x.py(13, 0): lambda:: (PhySL)
  [3]: x.py(15, 4): variable$b:: (PhySL)
```

**Comment by stevenrbrandt** [comment]
Also, this variation is important
```
from phylanx import Phylanx

@Phylanx
def foo2(a):
    a["groups"] = None

@Phylanx
def foo():
    a={"groups":1,"fish":2}
    b={"LEFT":a, "RIGHT":[3,4]}
    foo2(b["LEFT"])

foo()
```
which yields
```
Traceback (most recent call last):
  File "x.py", line 13, in <module>
    foo()
  File "/home/jovyan/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/transducer.py", line 191, in __call__
    result = self.backend.call(*mapped_args, **mapped_kwargs)
  File "/home/jovyan/.local/lib/python3.8/site-packages/phylanx-0.0.1-py3.8-linux-x86_64.egg/phylanx/ast/physl.py", line 598, in call
    result = phylanx.execution_tree.eval(
RuntimeError:
<stack frames>
  [1]: x.py: foo2:: (Python)
  [2]: x.py(8, 0): lambda:: (PhySL)
  [3]: x.py(4, 0): lambda:: (PhySL)
  [4]: x.py(5, 4): access-argument$a:: (PhySL)

storing a value to a local value has no effect: HPX(bad_parameter)
```

**Comment by hkaiser** [comment]
@stevenrbrandt currently parameters are always passed by value. So I'm not sure if we can solve this easily.

**Comment by stevenrbrandt** [comment]
@hkaiser and I don't think the Random Forest code can be made to work unless it is solved. :(

**Comment by hkaiser** [comment]
> @hkaiser and I don't think the Random Forest code can be made to work unless it is solved. :(

Any suggestions you might have would be welcome.

**Comment by stevenrbrandt** [comment]
Maybe a less ambitious random forest, one which leaves the dictionary manipulation to Python, might be possible.
--Steve
