### ISSUE TITLE
Python to PhySL Translation generates empty block

### ISSUE THREAD

**Issue by parsa** [STEllAR-GROUP/phylanx#278]
Observation:
```
$ python3 lra_csv_phyfun.py
RuntimeError: <unknown>(25, 8): block:: the block_operation primitive requires at least one argument: HPX(bad_parameter)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lra_csv_phyfun.py", line 35, in <module>
    res = lra("breast_cancer.csv", 0, 569, 0, 30, 0, 569, 30, 31, 1e-5, 750, 0)
  File "/root/.local/lib/python3.5/site-packages/phylanx-0.0.1-py3.5-linux-x86_64.egg/phylanx/ast/transformation.py", line 455, in __call__
    return et.eval(self.__physl_src__, *nargs)
SystemError: <built-in method eval of PyCapsule object at 0x7f16ec65e600> returned a result with an error set
```

Generated PhySL code:
```scheme
block$13$0(define$13$0(lra$13$0, file_name$13$8, xlo1$13$19, xhi1$13$25, ylo1$13$31, yhi1$13$37, xlo2$13$43, xhi2$13$49, ylo2$13$55, yhi2$13$61, alpha$13$67, iterations$14$8, enable_output$14$20, block$13$0(define$15$4(data$15$4,file_read_csv$15$11(file_name$15$25)), def
ine$16$4(x$16$4,slice$16$13(data$16$8,xlo1$16$13,xhi1$16$18,ylo1$16$24,yhi1$16$29)), define$17$4(y$17$4,slice$17$13(data$17$8,xlo2$17$13,xhi2$17$18,ylo2$17$24,yhi2$17$29)), define$18$4(weights$18$4,constant$18$14(0.0, shape$18$28(x$18$34, 1))), define$19$4(transx$19$4,tr
anspose$19$13(x$19$23)), define$20$4(pred$20$4,constant$20$11(0.0, shape$20$25(x$20$31, 0))), define$21$4(error$21$4,constant$21$12(0.0, shape$21$26(x$21$32, 0))), define$22$4(gradient$22$4,constant$22$15(0.0, shape$22$29(x$22$35, 1))), define$23$4(step$23$4,0), while(st
ep$24$10 < iterations$24$17,block$24$4(if(enable_output$25$11,cout$26$12("step: ", step$26$28, ", ", weights$26$40),block$25$8()), store$27$8(pred$27$8,(1.0 / (1.0 + exp$27$28(-(dot$27$33(x$27$37, weights$27$40)))))), store$28$8(error$28$8,(pred$28$16 - y$28$23)), store$
29$8(gradient$29$8,dot$29$19(transx$29$23, error$29$31)), store$30$8(weights$30$8,(weights$30$18 - (alpha$30$29 * gradient$30$37))), store$31$8(step$31$8,step$31$8+1))),  weights$32$11)), lra$13$0)
```
Generated PhySL code, formatted for readability:
```scheme
block$13$0(
    define$13$0(
        lra$13$0, file_name$13$8, xlo1$13$19, xhi1$13$25, ylo1$13$31, yhi1$13$37, xlo2$13$43, xhi2$13$49, ylo2$13$55, yhi2$13$61, alpha$13$67, iterations$14$8, enable_output$14$20,
        block$13$0(
            define$15$4(data$15$4,file_read_csv$15$11(file_name$15$25)),
                define$16$4(x$16$4,slice$16$13(data$16$8,xlo1$16$13,xhi1$16$18,ylo1$16$24,yhi1$16$29)),
                define$17$4(y$17$4,slice$17$13(data$17$8,xlo2$17$13,xhi2$17$18,ylo2$17$24,yhi2$17$29)),
                define$18$4(weights$18$4,constant$18$14(0.0, shape$18$28(x$18$34, 1))),
                define$19$4(transx$19$4,transpose$19$13(x$19$23)),
                define$20$4(pred$20$4,constant$20$11(0.0, shape$20$25(x$20$31, 0))),
                define$21$4(error$21$4,constant$21$12(0.0, shape$21$26(x$21$32, 0))),
                define$22$4(gradient$22$4,constant$22$15(0.0, shape$22$29(x$22$35, 1))),
                define$23$4(step$23$4,0),
                while(step$24$10 < iterations$24$17,
                        block$24$4(
                            if(enable_output$25$11,
                                    cout$26$12("step: ", step$26$28, ", ", weights$26$40),
                                    block$25$8()            # THIS IS THE EMPTY BLOCK
                            ),
                            store$27$8(pred$27$8,(1.0 / (1.0 + exp$27$28(-(dot$27$33(x$27$37, weights$27$40)))))),
                            store$28$8(error$28$8,(pred$28$16 - y$28$23)),
                            store$29$8(gradient$29$8,dot$29$19(transx$29$23, error$29$31)),
                            store$30$8(weights$30$8,(weights$30$18 - (alpha$30$29 * gradient$30$37))),
                            store$31$8(step$31$8,step$31$8+1)
                        )
                ),
                weights$32$11
        )
     ),
     lra$13$0
)
```

**Comment by hkaiser** [comment]
Should we support empty `block` expressions? Or would a special `nil` be more appropriate?

**Comment by stevenrbrandt** [comment]
We can simply fix this with a one line change
```
diff --git a/python/phylanx/ast/transformation.py b/python/phylanx/ast/transformation.py
index ea03ea9..2c0cff8 100644
--- a/python/phylanx/ast/transformation.py
+++ b/python/phylanx/ast/transformation.py
@@ -284,7 +284,7 @@ class PhySL:
         elif len(a.orelse) == 1:
             s += self.recompile(a.orelse[0], allowreturn)
         else:
-            s += "block" + symbol_info + "()"
+            s += "block" + symbol_info + "(0)"
         s += ")"
         return s
```

**Comment by hkaiser** [comment]
@stevenrbrandt it might be better to remove this check: https://github.com/STEllAR-GROUP/phylanx/blob/master/src/execution_tree/primitives/block_operation.cpp#L91.

**Comment by stevenrbrandt** [comment]
Sounds good. Let's do it.

**Comment by parsa** [comment]
@hkaiser done. See #290
