### ISSUE TITLE
Array subscripts are not supported on the LHS of assignments.

### ISSUE THREAD

**Issue by rtohid** [STEllAR-GROUP/phylanx#403]
The following example fails:
```py
import phylanx
from phylanx.ast import *


@Phylanx("PhySL")
def foo():
    v1 = [0, 0, 0]
    v1[1] = 1
    return v1

print(foo())
```

**Comment by hkaiser** [comment]
@stevenrbrandt Can this be closed now?

**Comment by rtohid** [comment]
This still fails with the following error (I also tried with `make_list` instead of brackets):
```
Traceback (most recent call last):
  File "set_op.py", line 5, in <module>
    @Phylanx
  File "/home/rod/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/transformation.py", line 669, in Phylanx
    return PhyTransformer(arg)
  File "/home/rod/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/transformation.py", line 656, in __init__
    et.compile(self.__src__, self.cs)
RuntimeError: <unknown>(1, 73): set:: primitive_argument_type does not hold a numeric value type (type held: 'phylanx::ir::range'): HPX(bad_parameter)
```

I also tried:
```py
import phylanx
from phylanx.ast import *


@Phylanx
def foo(v1):
    v1[1] = 1
    return v1

# Test 1
v = [0, 0, 0]
print(foo(v))

# Test 2
import numpy as np
v = np.array([0, 0, 0])
print(foo(v))
```
**Test 1** fails with the same error but **Test 2** passes. 

So I think `set_operation` only works on vectors- not lists.

**Comment by justwagle** [comment]
> So I think set_operation only works on vectors- not lists.

@rtohid Yes, that is true. Currently, set operation only works on vectors and I have already started working on adding list support to set and a few other changes that will make it more up to date.

**Comment by ct-clmsn** [comment]
@justwagle awesome! thanks!

**Comment by stevenrbrandt** [comment]
@hkaiser maybe we want to keep it open until @justwagle makes it work for lists?
