### ISSUE TITLE
Phylanx errors kill the interpreter

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#451]
The following kill the Python interpreter, when they should be rethrown as Python exceptions.
```python
from phylanx.ast import Phylanx

@Phylanx
def err():
    a = [1,2,3]
    a[2] = 2
```
and 
```python
from phylanx.ast import Phylanx

@Phylanx
def err():
    a = hstack(1,2,3)
    a[5] = 2

err()
```

**Comment by parsa** [comment]
Output for the first example
```
Traceback (most recent call last):
  File "C:\Repos\fnx.py-1\fnx.py-1\fnx.py_1.py", line 3, in <module>
    @Phylanx
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\transformation.py", line 673, in Phylanx
    return PhyTransformer(arg)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\transformation.py", line 660, in __init__
    et.compile(self.__src__, self.cs)
RuntimeError: <unknown>: set$0/0$1$72:: primitive_argument_type does not hold a numeric value type (type held: 'phylanx::ir::range'): HPX(bad_parameter)
```
Output for the second example:
```
Traceback (most recent call last):
  File "C:\Repos\fnx.py-1\fnx.py-1\fnx.py_1.py", line 3, in <module>
    @Phylanx
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\transformation.py", line 673, in Phylanx
    return PhyTransformer(arg)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\transformation.py", line 660, in __init__
    et.compile(self.__src__, self.cs)
ValueError: Invalid element access index
```

**Comment by parsa** [comment]
@stevenrbrandt I cannot reproduce your issue. In both examples I see a Python error.

**Comment by hkaiser** [comment]
The second error message misses the symbol information which is a bug that requires fixing.

**Comment by stevenrbrandt** [comment]
I updated HPX and this problem went away.
