### ISSUE TITLE
Can't call a Lambda

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#492]
The code
```
from phylanx.ast import Phylanx

@Phylanx
def foo():
    f = lambda a : print(a)
    f(1)

foo()
```
Yields the message
```
Traceback (most recent call last):
  File "lam.py", line 8, in <module>
    foo()
  File "/root/.local/lib/python3.5/site-packages/phylanx-0.0.1-py3.5-linux-x86_64.egg/phylanx/ast/transformation.py", line 689, in __call__
    return et.eval(self.f.__name__, self.cs, *nargs)
RuntimeError: <unknown>(5, 25): access-argument$a:: argument count out of bounds, expected at least 1 argument(s) while only 0 argument(s) were supplied: HPX(bad_parameter)
```
Apparently, the argument count is not correctly identified when calling lambdas. For reference, the PhySL code is here:
```
define(
    foo,
    block(
        define(
            f,
            lambda(
                a,
                block(
                    cout(a)
                )
            )
        ),
        (
            f(1)
        )
    )
)
```

**Comment by hkaiser** [comment]
@stevenrbrandt This is caused by the known flaw in the compiler that executes nullary function definitions at compile time. I'm working on a fix that will address this issue (amongst others).
