### ISSUE TITLE
len operation does not support np.array

### ISSUE THREAD

**Issue by weilewei** [STEllAR-GROUP/phylanx#494]
The code
```
@Phylanx(debug=True)
def Phylanx_len_test(input_para):
    local_input_para = input_para
    print("Phylanx precision: ", len(local_input_para), '\n')


def Python_len_test(input_para):
    print("Python len: ", len(input_para), '\n')


b = np.array([1, 2, 3])

Python_len_test(b)
Phylanx_len_test(b)
```
yields information:
```
define(
    Phylanx_len_test,
    input_para,
    block(
        define(local_input_para, input_para),
        (
            cout(
                "Phylanx precision: ",
                len(local_input_para),
                "
"
            )
        )
    )
)
Python len:  3 

Traceback (most recent call last):
  File "/root/PycharmProjects/nn/add_test.py", line 235, in <module>
    Phylanx_len_test(b)
  File "/root/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/transformation.py", line 685, in __call__
    return et.eval(self.f.__name__, self.cs, *nargs)
RuntimeError: <unknown>(225, 33): len:: len_operation accepts a list or a string as operand: HPX(bad_parameter)

Process finished with exit code 1
```

**Comment by hkaiser** [comment]
This is something that would have to be added here: https://github.com/STEllAR-GROUP/phylanx/blob/master/src/plugins/listops/len_operation.cpp#L76. Shouldn't be too problematic...
