### ISSUE TITLE
store function should only be called for the primitives that support it

### ISSUE THREAD

**Issue by weilewei** [STEllAR-GROUP/phylanx#513]
I expect the following code can return `2` for `a`, but it failed.
The code
```py
from phylanx.ast import *
import numpy as np


@Phylanx
def foo1(x):
    x += 1
    return x


a = 1
foo1(a)
```
complains
```py
Traceback (most recent call last):
  File "PATH/PycharmProjects/nn/add_test.py", line 12, in <module>
    foo1(a)
  File "PATH/.local/lib/python3.6/site-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/transformation.py", line 702, in __call__
    return et.eval(self.f.__name__, self.cs, *nargs)
RuntimeError: <unknown>(7, 4): access-argument$x:: store function should only be called for the primitives that support it (e.g. variables): HPX(invalid_status)

Process finished with exit code 1

```

**Comment by hkaiser** [comment]
This is a known issue (has been reported before here: #482). Closing.
