### ISSUE TITLE
Random test failures for Phylanx programs due to command line processing

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/phylanx#712]
On the buildbot server, the tests occasionally fail.  Not always the same test.  The failures look something like this (when using ctest to re-run the test over and over again until it fails):

```console
[buildbot@delphi phylanx-Release]$ ctest -V -R tests.regressions.python.python.list_iter_space_429
UpdateCTestConfiguration  from :/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/DartConfiguration.tcl
Parse Config file:/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/DartConfiguration.tcl
UpdateCTestConfiguration  from :/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/DartConfiguration.tcl
Parse Config file:/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/DartConfiguration.tcl
Test project /var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 47
    Start 47: tests.regressions.python.python.list_iter_space_429

47: Test command: /packages/python/3.6.4-ssl/bin/python3 "/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/tests/regressions/python/list_iter_space_429.py"
47: Environment variables: 
47:  PYTHONPATH=/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/python/build/lib.linux-x86_64-3.6
47: Test timeout computed to be: 1500
47: Traceback (most recent call last):
47:   File "/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/tests/regressions/python/list_iter_space_429.py", line 19, in <module>
47:     assert f1() == 0
47:   File "/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/python/build/lib.linux-x86_64-3.6/phylanx/ast/transducer.py", line 82, in __call__
47:     result = self.backend.call(args)
47:   File "/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/python/build/lib.linux-x86_64-3.6/phylanx/ast/physl.py", line 292, in call
47:     PhylanxSession.init(1)
47:   File "/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-release/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/python/build/lib.linux-x86_64-3.6/phylanx/core/config.py", line 33, in init
47:     init_hpx_runtime(PhylanxSession.cfg)
47: RuntimeError: Cannot parse line at:  <command line definitions>: line 30 (offending entry: hpx.cmd_line!="arg
47: Args:
47: 
47:     arg (matrix or vector of numbers) : the input values
47: 
47: Returns:
47: 
47: True if all values in the matrix/vector are nonzero,
47: False otherwise.
47: "): HPX(no_success)
1/1 Test #47: tests.regressions.python.python.list_iter_space_429 ...***Failed    1.33 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.37 sec

The following tests FAILED:
	 47 - tests.regressions.python.python.list_iter_space_429 (Failed)
Errors while running CTest
```

**Comment by hkaiser** [comment]
@khuck could this be a strange follow-up error happening after a stack-overflow or similarly catastrophic event? The same is happening for the RelWithDebInfo build on KNL, btw (see http://ktau.nic.uoregon.edu:8020/#/builders/3/builds/109/steps/12/logs/stdio).

**Comment by hkaiser** [comment]
After staring at the relevant code for a while - we retrieve (or at least we attempt to) the command line options from `/proc/self/cmdline`. Let's add some logging to the code that initializes `__argv`/`__argc` here: https://github.com/STEllAR-GROUP/phylanx/blob/master/python/src/init_hpx.cpp#L25-L84. That might give us some further clues.

**Comment by khuck** [comment]
@hkaiser I haven't really investigated it yet, but I assume it's something transient, it doesn't reproduce all the time.  But over the ~180 tests, at least one fails each time.  It might be worthwhile checking for memory errors with the address sanitizer (like referencing a variable that has gone out of scope).

**Comment by khuck** [comment]
This seems to be fixed?  I am not seeing it any more.
