### ISSUE TITLE
tests.regressions.python.python.exception_swallowed_369 throwing different exception than the one expected

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/phylanx#775]
The expected exception is:

```
    expected = \
        'exception_swallowed_369.py(14, 8): __add:: cannot broadcast a ' + \
        'matrix into a differently sized matrix: HPX(bad_parameter)'
```

but the actual output is:  ```RuntimeError: %1%%2%: %3%:: %4%: HPX(bad_parameter)```

```
[khuck@delphi phylanx-Release]$ ctest -V -R tests.regressions.python.python.exception_swallowed_369
UpdateCTestConfiguration  from :/dev/shm/now/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/DartConfiguration.tcl
Parse Config file:/dev/shm/now/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/DartConfiguration.tcl
UpdateCTestConfiguration  from :/dev/shm/now/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/DartConfiguration.tcl
Parse Config file:/dev/shm/now/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/DartConfiguration.tcl
Test project /dev/shm/now/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 45
    Start 45: tests.regressions.python.python.exception_swallowed_369

45: Test command: /packages/python/3.6.4-ssl/bin/python3 "/dev/shm/now/phylanx/tests/regressions/python/exception_swallowed_369.py"
45: Environment variables: 
45:  PYTHONPATH=/dev/shm/now/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/python/build/lib.linux-x86_64-3.6
45: Test timeout computed to be: 1500
45: Traceback (most recent call last):
45:   File "/dev/shm/now/phylanx/tests/regressions/python/exception_swallowed_369.py", line 21, in <module>
45:     print('addem=(', addem(np.zeros((2, 4)), np.zeros((2, 3))), ')')
45:   File "/dev/shm/now/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/python/build/lib.linux-x86_64-3.6/phylanx/ast/transducer.py", line 82, in __call__
45:     result = self.backend.call(args)
45:   File "/dev/shm/now/phylanx/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-Release/python/build/lib.linux-x86_64-3.6/phylanx/ast/physl.py", line 369, in call
45:     self.file_name, func_name, PhySL.compiler_state, *args)
45: RuntimeError: %1%%2%: %3%:: %4%: HPX(bad_parameter)
45: 
45: During handling of the above exception, another exception occurred:
45: 
45: Traceback (most recent call last):
45:   File "/dev/shm/now/phylanx/tests/regressions/python/exception_swallowed_369.py", line 27, in <module>
45:     assert (str(e).endswith(expected))
45: AssertionError
1/1 Test #45: tests.regressions.python.python.exception_swallowed_369 ...***Failed    1.65 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.69 sec

The following tests FAILED:
	 45 - tests.regressions.python.python.exception_swallowed_369 (Failed)
Errors while running CTest
```

**Comment by khuck** [comment]
Same is true for out_of_scope_variable_232: 

```
/dev/shm/now/phylanx/tests/regressions/execution_tree/out_of_scope_variable_232.cpp(39): test 'std::string(e.what()) == "code(5, 13): couldn't find variable 'n' in symbol table: " "HPX(bad_parameter)"' failed in function 'int main(int, char**)': '%1%(%2%, %3%): %4%: HPX(bad_parameter)' != 'code(5, 13): couldn't find variable 'n' in symbol table: HPX(bad_parameter)'
```

**Comment by hkaiser** [comment]
@khuck is this happening on master or on some other branch?

**Comment by khuck** [comment]
@hkaiser master (the third failure here is because master doesn't have the extract_function_name() fix yet), commit e8e6cbbdaedbfd5a7860098d1648e8b4e24da574.
```
The following tests FAILED:
	 19 - tests.regressions.execution_tree.out_of_scope_variable_232 (Failed)
	 45 - tests.regressions.python.python.exception_swallowed_369 (Failed)
	 88 - tests.unit.plugins.arithmetics.generic_operation (Failed)
Errors while running CTest
```

**Comment by hkaiser** [comment]
@khuck this turns out to be a problem in HPX, should be fixed once https://github.com/STEllAR-GROUP/hpx/pull/3677 will be merged.

**Comment by khuck** [comment]
@hkaiser awesome, thanks!
