### ISSUE TITLE
RelWithDebInfo transient errors from tests.regressions.python.python.list_iteration_524

### ISSUE THREAD

**Issue by khuck** [STEllAR-GROUP/phylanx#776]
This test *sometimes* fails with gcc 7.1, RelWithDebInfo build on x86_64.  The tests.unit.python.execution_tree.eval test has shown a similar behavior.

The first run example gives a ```48: hpx::init: command line warning: command line options file not found (?)``` warning, but runs without an error:

```console
[buildbot@delphi phylanx-RelWithDebInfo]$ ctest -V -R tests.regressions.python.python.list_iteration_524
UpdateCTestConfiguration  from :/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
Parse Config file:/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
UpdateCTestConfiguration  from :/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
Parse Config file:/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
Test project /var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 48
    Start 48: tests.regressions.python.python.list_iteration_524

48: Test command: /packages/python/3.6.4-ssl/bin/python3 "/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tests/regressions/python/list_iteration_524.py"
48: Environment variables: 
48:  PYTHONPATH=/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/python/build/lib.linux-x86_64-3.6
48: Test timeout computed to be: 1500
48: hpx::init: command line warning: command line options file not found (?)
1/1 Test #48: tests.regressions.python.python.list_iteration_524 ...   Passed    1.71 sec

The following tests passed:
	tests.regressions.python.python.list_iteration_524

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   1.74 sec
```

The second run, the warning goes away:

```console
[buildbot@delphi phylanx-RelWithDebInfo]$ ctest -V -R tests.regressions.python.python.list_iteration_524
UpdateCTestConfiguration  from :/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
Parse Config file:/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
UpdateCTestConfiguration  from :/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
Parse Config file:/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
Test project /var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 48
    Start 48: tests.regressions.python.python.list_iteration_524

48: Test command: /packages/python/3.6.4-ssl/bin/python3 "/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tests/regressions/python/list_iteration_524.py"
48: Environment variables: 
48:  PYTHONPATH=/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/python/build/lib.linux-x86_64-3.6
48: Test timeout computed to be: 1500
1/1 Test #48: tests.regressions.python.python.list_iteration_524 ...   Passed    1.51 sec

The following tests passed:
	tests.regressions.python.python.list_iteration_524

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   1.54 sec
```

The third test fails:

```console
[buildbot@delphi phylanx-RelWithDebInfo]$ ctest -V -R tests.regressions.python.python.list_iteration_524
UpdateCTestConfiguration  from :/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
Parse Config file:/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
UpdateCTestConfiguration  from :/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
Parse Config file:/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/DartConfiguration.tcl
Test project /var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo
Constructing a list of tests
Done constructing a list of tests
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 48
    Start 48: tests.regressions.python.python.list_iteration_524

48: Test command: /packages/python/3.6.4-ssl/bin/python3 "/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tests/regressions/python/list_iteration_524.py"
48: Environment variables: 
48:  PYTHONPATH=/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/python/build/lib.linux-x86_64-3.6
48: Test timeout computed to be: 1500
48: Traceback (most recent call last):
48:   File "/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tests/regressions/python/list_iteration_524.py", line 20, in <module>
48:     assert (foo(a) == [7, 8, 5, 6, 3, 4])
48:   File "/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/python/build/lib.linux-x86_64-3.6/phylanx/ast/transducer.py", line 82, in __call__
48:     result = self.backend.call(args)
48:   File "/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/python/build/lib.linux-x86_64-3.6/phylanx/ast/physl.py", line 350, in call
48:     PhylanxSession.init(1)
48:   File "/var/lib/buildbot/slaves/phylanx/x86_64-gcc7-relwithdebinfo/build/tools/buildbot/build-delphi-x86_64-Linux-gcc/phylanx-RelWithDebInfo/python/build/lib.linux-x86_64-3.6/phylanx/core/config.py", line 33, in init
48:     init_hpx_runtime(PhylanxSession.cfg)
48: RuntimeError: Cannot parse line at:  <command line definitions>: line 31 (offending entry: hpx.cmd_line!="
48:             m
48:             Args:
48: 
48:                 m (matrix): a scalar, matrix, or tensor
48: 
48:             Returns:
48: 
48:             The multiplicative inverse of m."): HPX(no_success)
1/1 Test #48: tests.regressions.python.python.list_iteration_524 ...***Failed    1.58 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   1.62 sec

The following tests FAILED:
	 48 - tests.regressions.python.python.list_iteration_524 (Failed)
Errors while running CTest
```

**Comment by khuck** [comment]
This issue apparently has been fixed.
