### ISSUE TITLE
Phylanx Performance Data Broken

### ISSUE THREAD

**Issue by stevenrbrandt** [STEllAR-GROUP/phylanx#832]
The following code no longer works:
```
from phylanx import Phylanx

@Phylanx(performance="x")
def fib(n):
    if n < 2:
        return n
    else:
        return fib(n-1)+fib(n-2)

fib(10)
```
Error message is:
```
Traceback (most recent call last):
  File "x.py", line 11, in <module>
    fib(10)
  File "/usr/local/lib/python3.6/dist-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/transducer.py", line 94, in __call__
    result = self.backend.call(args)
  File "/usr/local/lib/python3.6/dist-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 465, in call
    return self.lazy(args).eval()
  File "/usr/local/lib/python3.6/dist-packages/phylanx-0.0.1-py3.6-linux-x86_64.egg/phylanx/ast/physl.py", line 432, in eval
    *self.args)
RuntimeError: invalid reference id: HPX(bad_parameter)
```

**Comment by stevenrbrandt** [comment]
```
#0  0x00007feabcbc5611 in __cxa_throw () from /lib64/libstdc++.so.6
#1  0x00007feac1f5a81b in pybind11::detail::type_caster_base<phylanx::bindings::compiler_state>::operator phylanx::bindings::compiler_state& (
    this=0x7ffe3c5819c8) at /usr/local/include/pybind11/cast.h:884
#2  0x00007feac1f56977 in pybind11::detail::cast_op<phylanx::bindings::compiler_state&> (caster=...) at /usr/local/include/pybind11/cast.h:919
#3  0x00007feac1f50d01 in pybind11::detail::argument_loader<phylanx::bindings::compiler_state&, bool>::call_impl<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (*&)(phylanx::bindings::compiler_state&, bool), 0ul, 1ul, pybind11::detail::void_type> (this=0x7ffe3c5819c0, f=
    @0x974498: 0x7feac1f0f4cb <phylanx::bindings::enable_measurements[abi:cxx11](phylanx::bindings::compiler_state&, bool)>)
    at /usr/local/include/pybind11/cast.h:1931
#4  0x00007feac1f4daf0 in pybind11::detail::argument_loader<phylanx::bindings::compiler_state&, bool>::call<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, pybind11::detail::void_type, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (*&)(phylanx::bindings::compiler_state&, bool)>(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (*&)(phylanx::bindings::compiler_state&, bool)) && (this=0x7ffe3c5819c0, 
    f=@0x974498: 0x7feac1f0f4cb <phylanx::bindings::enable_measurements[abi:cxx11](phylanx::bindings::compiler_state&, bool)>)
    at /usr/local/include/pybind11/cast.h:1908
#5  0x00007feac1f462f3 in pybind11::cpp_function::initialize<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (*&)(phylanx::bindings::compiler_state&, bool), std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, phylanx::bindings::compiler_state&, bool, pybind11::name, pybind11::scope, pybind11::sibling, char [63]>(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (*&)(phylanx::bindings::compiler_state&, bool), std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (*)(phylanx::bindings::compiler_state&, bool), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, char const (&) [63])::{lambda(pybind11::detail::function_call&)#3}::operator()(pybind11::detail::function_call&) const (this=0x0, call=...) at /usr/local/include/pybind11/pybind11.h:155
#6  0x00007feac1f46445 in pybind11::cpp_function::initialize<std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (*&)(phylanx::bindings::compiler_state&, bool), std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, phylanx::bindings::compiler_state&, bool, pybind11::name, pybind11::scope, pybind11::sibling, char [63]>(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (*&)(phylanx::bindings::compiler_state&, bool), std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > (*)(phylanx::bindings::compiler_state&, bool), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&, char const (&) [63])::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call&) () at /usr/local/include/pybind11/pybind11.h:133
#7  0x00007feac1e2dfdb in pybind11::cpp_function::dispatcher (self=0x7feac20affc0, args_in=0x7fea1961c6c8, kwargs_in=0x0) at /usr/local/include/pybind11/pybind11.h:620
#8  0x000000000049a8ba in _PyCFunction_FastCallDict (func_obj=0x7feac20b0828, args=0xce7800, nargs=<optimized out>, kwargs=kwargs@entry=0x0) at Objects/methodobject.c:231
#9  0x000000000049aab3 in _PyCFunction_FastCallKeywords (func=func@entry=0x7feac20b0828, stack=<optimized out>, nargs=nargs@entry=2, kwnames=kwnames@entry=0x0) at Objects/methodobject.c:294
#10 0x00000000005256cf in call_function (pp_stack=pp_stack@entry=0x7ffe3c582110, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4837
#11 0x000000000052ad26 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3335
#12 0x000000000052449c in PyEval_EvalFrameEx (throwflag=0, f=0xce7658) at Python/ceval.c:754
#13 _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=nargs@entry=2, globals=globals@entry=0x7feac20dba68) at Python/ceval.c:4919
#14 0x00000000005257a1 in fast_function (kwnames=0x0, nargs=2, stack=<optimized out>, func=0x7fea1960b2f0) at Python/ceval.c:4954
#15 call_function (pp_stack=pp_stack@entry=0x7ffe3c5822c0, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4858
#16 0x000000000052ad26 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3335
#17 0x00000000005251f4 in PyEval_EvalFrameEx (throwflag=0, f=0xce8598) at Python/ceval.c:754
#18 _PyEval_EvalCodeWithName (_co=_co@entry=0x7feac21abe40, globals=globals@entry=0x7feac21d4b88, locals=locals@entry=0x0, args=args@entry=0x7ffe3c582550, argcount=argcount@entry=1, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x7feac23fa170, qualname=0x7feac2140e10) at Python/ceval.c:4166
#19 0x000000000052e304 in _PyFunction_FastCallDict (func=func@entry=0x7fea19611ea0, args=args@entry=0x7ffe3c582550, nargs=nargs@entry=1, kwargs=kwargs@entry=0x0) at Python/ceval.c:5070
#20 0x0000000000449021 in _PyObject_FastCallDict (func=0x7fea19611ea0, args=0x7ffe3c582550, nargs=1, kwargs=0x0) at Objects/abstract.c:2310
#21 0x000000000044924a in _PyObject_Call_Prepend (func=0x7fea19611ea0, obj=<optimized out>, args=0x7feac23f7048, kwargs=0x0) at Objects/abstract.c:2373
#22 0x0000000000448dfa in PyObject_Call (func=0x7feac23e9a88, args=<optimized out>, kwargs=<optimized out>) at Objects/abstract.c:2261
#23 0x00000000004b38df in slot_tp_call (self=0x7feac21d0cf8, args=0x7feac23f7048, kwds=0x0) at Objects/typeobject.c:6207
#24 0x0000000000448f82 in _PyObject_FastCallDict (func=0x7feac21d0cf8, args=0x85e838, nargs=0, kwargs=0x0) at Objects/abstract.c:2331
#25 0x00000000005253b8 in call_function (pp_stack=pp_stack@entry=0x7ffe3c582760, oparg=<optimized out>, kwnames=kwnames@entry=0x0) at Python/ceval.c:4861
#26 0x000000000052ad26 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at Python/ceval.c:3335
#27 0x00000000005251f4 in PyEval_EvalFrameEx (throwflag=0, f=0x85e6b8) at Python/ceval.c:754
#28 _PyEval_EvalCodeWithName (_co=_co@entry=0x7feac2328810, globals=globals@entry=0x0, locals=locals@entry=0x7feac23ae168, args=args@entry=0x0, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=0x0, kwcount=0, kwstep=2, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name=0x0, qualname=0x0) at Python/ceval.c:4166
#29 0x0000000000525f63 in PyEval_EvalCodeEx (closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwcount=0, kws=0x0, argcount=0, args=0x0, locals=locals@entry=0x7feac23ae168, globals=globals@entry=0x0, _co=_co@entry=0x7feac2328810) at Python/ceval.c:4187
#30 PyEval_EvalCode (co=co@entry=0x7feac2328810, globals=globals@entry=0x7feac23ae168, locals=locals@entry=0x7feac23ae168) at Python/ceval.c:731
#31 0x00000000004267b2 in run_mod (arena=0x7feac23c8270, flags=0x7ffe3c582a2c, locals=0x7feac23ae168, globals=0x7feac23ae168, filename=0x7feac22e8180, mod=0x83ede8) at Python/pythonrun.c:1025
#32 PyRun_FileExFlags (fp=<optimized out>, filename_str=<optimized out>, start=<optimized out>, globals=0x7feac23ae168, locals=0x7feac23ae168, closeit=1, flags=0x7ffe3c582a2c) at Python/pythonrun.c:978
#33 0x0000000000426933 in PyRun_SimpleFileExFlags (fp=fp@entry=0x852610, filename=<optimized out>, closeit=closeit@entry=1, flags=flags@entry=0x7ffe3c582a2c) at Python/pythonrun.c:419
#34 0x0000000000426dbb in PyRun_AnyFileExFlags (fp=fp@entry=0x852610, filename=<optimized out>, closeit=closeit@entry=1, flags=flags@entry=0x7ffe3c582a2c) at Python/pythonrun.c:81
#35 0x0000000000436a59 in run_file (p_cf=0x7ffe3c582a2c, filename=0x8047e0 L"y.py", fp=0x852610) at Modules/main.c:340
#36 Py_Main (argc=argc@entry=2, argv=argv@entry=0x7ff260) at Modules/main.c:810
#37 0x000000000041d670 in main (argc=2, argv=<optimized out>) at ./Programs/python.c:69
Detaching from program: /usr/local/bin/python3.6, process 242
[Inferior 1 (process 242) detached]
```
