### ISSUE TITLE
The dtype of a variable is `object`

### ISSUE THREAD

**Issue by taless474** [STEllAR-GROUP/phylanx#903]
In the following code:
```py
import numpy as np
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)
	
def variable(value, dtype=None, name=None):
    return execution_tree.var(np.array(value, dtype=dtype))
	
def dtype(x):
	return execution_tree.var(x).dtype
	
@Phylanx
def arange_eager(start, stop, step, dtype):
	return np.arange(start, stop=stop, step=step, dtype=dtype)

def arange(start, stop=None, step=1, dtype='int32'):
	return arange_eager.lazy(start, stop, step, dtype)
	
def test_dtype_1():
	assert dtype(variable(1, dtype='float64')) == 'float64'
	assert dtype(variable(1, dtype='float32')) == 'float32'
	assert dtype(variable(1, dtype='float16')) == 'float16'
test_dtype_1()

def test_dtype_2():
	for dtype in ('int32', 'int64', 'float32', 'float64'):
		t = arange(10, dtype=dtype)
		assert dtype(t) == dtype
test_dtype_2()
```
we get assertion error. If we use another name for the `dtype(x)` as in the below example:
```py
def dt(x):
	return execution_tree.var(x).dtype

def test_dtype_1():
	return dt(variable(1, dtype='float64'))
```
we get this result:
```pytb
object
```

**Comment by hkaiser** [comment]
@taless474 Looks like that wrapping a Phylanx variable in a Phylanx variable needs to be handled explicitly (i.e. `execution_tree.variable(execution_tree.variable(x))` should be equivalent to `execution_tree.variable(x)`. That should solve the second issue you're describing. I will need to see the assertion to understand what's going wrong in the first case.

**Comment by taless474** [comment]
Thank you for your response. Having only `test_dtype_1()`
```py
import numpy as np
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)
	
def variable(value, dtype=None, name=None):
    return execution_tree.var(np.array(value, dtype=dtype))
	
def dtype(x):
	return execution_tree.var(x).dtype
	
def test_dtype_1():
	assert dtype(variable(1, dtype='float64')) == 'float64'
	assert dtype(variable(1, dtype='float32')) == 'float32'
	assert dtype(variable(1, dtype='float16')) == 'float16'
test_dtype_1()
```
 results in:
```pytb
Traceback (most recent call last):
  File "test31.py", line 32, in <module>
    print(test_dtype_1())
  File "test31.py", line 28, in test_dtype_1
    assert dtype(variable(1, dtype='float64')) == 'float64'
AssertionError
```
And having only `test_dtype_2()` 
```py
import numpy as np
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)
	
def variable(value, dtype=None, name=None):
    return execution_tree.var(np.array(value, dtype=dtype))
	
def dtype(x):
	return execution_tree.var(x).dtype
	
@Phylanx
def arange_eager(start, stop, step, dtype):
	return np.arange(start, stop=stop, step=step, dtype=dtype)

def arange(start, stop=None, step=1, dtype='int32'):
	return arange_eager.lazy(start, stop, step, dtype)

def test_dtype_2():
	for dtype in ('int32', 'int64', 'float32', 'float64'):
		t = arange(10, dtype=dtype)
		assert dtype(t) == dtype
test_dtype_2()
```
results in:
```pytb
Traceback (most recent call last):
  File "test31.py", line 49, in <module>
    print(test_dtype_2())
  File "test31.py", line 46, in test_dtype_2
    assert dtype(t) == dtype
TypeError: 'str' object is not callable
```

**Comment by hkaiser** [comment]
Well, the second case is just invalid Python code, as `dtype` in the assert refers to the local variable instead of the global function of the same name.

**Comment by taless474** [comment]
You are right. I shouldn't have simplified it into one file.
```py
import theOtherModule as K
def test_dtype_2():
	for dtype in ('int32', 'int64', 'float32', 'float64'):
		t = K.arange(10, dtype=dtype)
		assert K.dtype(t) == dtype
		
print(test_dtype_2())
```
results in:
```pytb
Traceback (most recent call last):
  File "test35.py", line 8, in <module>
    print(test_dtype_2())
  File "test35.py", line 5, in test_dtype_2
    assert K.dtype(t) == dtype
  File "C:\Users\Bita\Desktop\New folder\test34.py", line 13, in dtype
    return execution_tree.var(x).dtype
TypeError: var(): incompatible function arguments. The following argument types are supported:
    1. (_phylanxd.execution_tree.primitive_argument_type) -> arg0: phylanx::execution_tree::primitive
    2. (arg0: str) -> phylanx::execution_tree::primitive
    3. (arg0: float) -> phylanx::execution_tree::primitive
    4. (arg0: List[float]) -> phylanx::execution_tree::primitive
    5. (arg0: List[List[float]]) -> phylanx::execution_tree::primitive
    6. (arg0: List[List[List[float]]]) -> phylanx::execution_tree::primitive
    7. (arg0: int) -> phylanx::execution_tree::primitive
    8. (arg0: List[int]) -> phylanx::execution_tree::primitive
    9. (arg0: List[List[int]]) -> phylanx::execution_tree::primitive
    10. (arg0: List[List[List[int]]]) -> phylanx::execution_tree::primitive
    11. (arg0: int) -> phylanx::execution_tree::primitive
    12. (arg0: List[int]) -> phylanx::execution_tree::primitive
    13. (arg0: List[List[int]]) -> phylanx::execution_tree::primitive
    14. (arg0: List[List[List[int]]]) -> phylanx::execution_tree::primitive
    15. (arg0: none) -> phylanx::execution_tree::primitive

Invoked with: <phylanx.ast.physl.PhySL.eval_wrapper object at 0x000001D0223E9780>
```

**Comment by taless474** [comment]
The following code:
```py
import numpy as np
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)

def dtype(x):
	return execution_tree.variable(x).dtype

@Phylanx
def arange_eager(start, stop, step, dtype):
	return np.arange(start, stop=stop, step=step, dtype=dtype)

def arange(start, stop=None, step=1, dtype='int32'):
	return arange_eager.lazy(start, stop, step, dtype)

def test_dtype_2():
	for dt in ('int32', 'int64', 'float32', 'float64'):
		t = arange(10, dtype=dt)
		assert dtype(t) == dt

test_dtype_2()
```
results in:
```pytb
Traceback (most recent call last):
  File "test31.py", line 50, in <module>
    print(test_dtype_2())
  File "test31.py", line 47, in test_dtype_2
    assert dtype(t) == dt
  File "test31.py", line 18, in dtype
    return execution_tree.variable(x).dtype
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. phylanx._phylanxd.execution_tree.variable(arg0: phylanx._phylanxd.execution_tree.variable)
    2. phylanx._phylanxd.execution_tree.variable(value: phylanx::execution_tree::primitive, dtype: object=None, name: object=None, constraint: object=None)
    3. phylanx._phylanxd.execution_tree.variable(value: array, dtype: object=None, name: object=None, constraint: object=None)
    4. phylanx._phylanxd.execution_tree.variable(value: str, dtype: object=None, name: object=None, constraint: object=None)
    5. phylanx._phylanxd.execution_tree.variable(_phylanxd.execution_tree.primitive_argument_type, value: object, dtype: object=None, name: object=None)

Invoked with: <phylanx.ast.physl.PhySL.eval_wrapper object at 0x000001520C9060B8>
```
I pass `dtype` to `arange`, but it seems not to work (there is no call to variable here).

**Comment by hkaiser** [comment]
@taless474 after thinking about this some more I believe it would be easiest to change the implementation of the `dtype()` function to:
```
def dtype(x):
    import phylanx.ast.physl.PhySL as PhySL
    if isintance(x, PhySL.eval_wrapper):
        code = PhySL.compiler_state.code_for(x.func_name)
        return execution_tree.var(code).dtype
    return execution_tree.var(x).dtype
```
The same would be necessary wherever a `execution_tree.variable()` is constructed.
