### ISSUE TITLE
Can't pass eval_wrapper directly to a variable()

### ISSUE THREAD

**Issue by hkaiser** [STEllAR-GROUP/phylanx#933]
The following code:
```py
import numpy as np
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)

def dtype(x):
	return execution_tree.variable(x).dtype

@Phylanx
def arange_eager(start, stop, step, dtype):
	return np.arange(start, stop=stop, step=step, dtype=dtype)

def arange(start, stop=None, step=1, dtype='int32'):
	return arange_eager.lazy(start, stop, step, dtype)

def test_dtype_2():
	for dt in ('int32', 'int64', 'float32', 'float64'):
		t = arange(10, dtype=dt)
		assert dtype(t) == dt

test_dtype_2()
```
results in:
```pytb
Traceback (most recent call last):
  File "test31.py", line 50, in <module>
    print(test_dtype_2())
  File "test31.py", line 47, in test_dtype_2
    assert dtype(t) == dt
  File "test31.py", line 18, in dtype
    return execution_tree.variable(x).dtype
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. phylanx._phylanxd.execution_tree.variable(arg0: phylanx._phylanxd.execution_tree.variable)
    2. phylanx._phylanxd.execution_tree.variable(value: phylanx::execution_tree::primitive, dtype: object=None, name: object=None, constraint: object=None)
    3. phylanx._phylanxd.execution_tree.variable(value: array, dtype: object=None, name: object=None, constraint: object=None)
    4. phylanx._phylanxd.execution_tree.variable(value: str, dtype: object=None, name: object=None, constraint: object=None)
    5. phylanx._phylanxd.execution_tree.variable(_phylanxd.execution_tree.primitive_argument_type, value: object, dtype: object=None, name: object=None)

Invoked with: <phylanx.ast.physl.PhySL.eval_wrapper object at 0x000001520C9060B8>
```
I pass `dtype` to `arange`, but it seems not to work (there is no call to variable here).

_Originally posted by @taless474 in https://github.com/STEllAR-GROUP/phylanx/issues/903#issuecomment-478688142_

**Comment by hkaiser** [comment]
@taless474 after thinking about this some more I believe it would be easiest to change the implementation of the `dtype()` function to:
```
def dtype(x):
    import phylanx.ast.physl.PhySL as PhySL
    if isinstance(x, PhySL.eval_wrapper):
        return execution_tree.variable(x.code()).dtype
    return execution_tree.variable(x).dtype
```
The same would be necessary wherever a `execution_tree.variable()` is constructed.

_Originally posted by @hkaiser in https://github.com/STEllAR-GROUP/phylanx/issues/903#issuecomment-478793756_

This will require to expose the `.code()` functionality from `eval_wrapper`
