### ISSUE TITLE
Add support for aggregation function to execution_tree.variable

### ISSUE THREAD

**Issue by taless474** [STEllAR-GROUP/phylanx#936]
The following test expects the variable to be compatible with `*`:
```py
import numpy as np
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)
	
_FLOATX = "float64"

def floatx():
	return _FLOATX
	
def variable(value, dtype=None, name=None, constraint=None):
	if dtype is None:
		dtype = floatx()
	from phylanx.ast.physl import PhySL
	if isinstance(value, PhySL.eval_wrapper):
		return execution_tree.variable(value.code(), dtype)
	if isinstance(value, execution_tree.variable):
		return value
	return execution_tree.variable(value, dtype=dtype, name=name)
	
def eval(x):
	return x.eval()
	
@Phylanx
def greater_equal_eager(x, y):
	return x >= y

def greater_equal(x, y):
	return greater_equal_eager.lazy(x, y)
	
@Phylanx
def switch_eager(condition, then_expression, else_expression):
	return switch(condition, then_expression, else_expression)
	
def switch(condition, then_expression, else_expression):
	return switch_eager.lazy(condition, then_expression, else_expression)

def test_switch():
	val = np.random.random()
	x = variable(val)
	x = switch(greater_equal(x, 0.5), x * 0.1, x * 0.2)
        return eval(x)

test_switch()
```
```pytb
Traceback (most recent call last):
  File "test41.py", line 77, in <module>
    test_switch()
  File "test41.py", line 61, in test_switch
    x = switch(greater_equal(x, 0.5), x * 0.1, x * 0.2)
TypeError: unsupported operand type(s) for *: 'phylanx._phylanxd.execution_tree.variable' and 'float'
```

**Comment by taless474** [comment]
Another attribute a variable should have is `callable`:
```py
import numpy as np
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)

def variable(value, dtype=None, name=None, constraint=None):
	if dtype is None:
		dtype = "float32"
	if constraint is not None:
		raise TypeError("Constraint is the projection function to be "
						"applied to the variable after an optimizer update")
	from phylanx.ast.physl import PhySL
	if isinstance(value, PhySL.eval_wrapper):
		return execution_tree.variable(value.code(), dtype)
	if isinstance(value, execution_tree.variable):
		return value
	return execution_tree.variable(value, dtype=dtype, name=name)
	
def eval(func):
    return func.eval()
	
_LEARNING_PHASE = True

def learning_phase():
	return _LEARNING_PHASE

@Phylanx	
def in_train_phase_eager(x, alt, training=None):
	if training == 1 or training == True:
		if callable(x):
			return x()
		else:
			return x
	else:
		if callable(alt):
			return alt()
		else:
			return alt

	
def in_train_phase(x, alt, training=None):
	if training is None:
		training = learning_phase()
	return in_train_phase_eager.lazy(x, alt, training)
	
def parse_shape_or_val(shape_or_val):
	return shape_or_val, np.random.random(shape_or_val).astype(np.float32) - 0.5
	
def test_in_train_phase(x_shape_or_val, y_shape_or_val, training):
	x_shape, x_val = parse_shape_or_val(x_shape_or_val)
	y_shape, y_val = parse_shape_or_val(y_shape_or_val)
	t = in_train_phase(variable(x_val), variable(y_val), training)
	return eval(t)
	
test_in_train_phase((3,3),(2,2))
test_in_train_phase((3,3),(2,2), False)
```

**Comment by taless474** [comment]
#950 fixed this.
As everything is callable in Phylanx, I wrote `in_train_phase` as this:
```py
@Phylanx
def in_train_phase_eager(x, alt, training=None):
	if training == 1 or training == True:
		return x()
	else:
		return alt()


def in_train_phase(x, alt, training=None):
	if training is None:
		training = learning_phase()
	return in_train_phase_eager.lazy(x, alt, training)
```
