### ISSUE TITLE
`fold` raises a type error passing a NumPy random array as `elems`

### ISSUE THREAD

**Issue by taless474** [STEllAR-GROUP/phylanx#940]
```py
import numpy as np
from phylanx import Phylanx

@Phylanx
def foldl(fn, elems, initializer=None):
	return fold_left(fn, initializer, elems)
	
	
x = np.array([[ 0.15627744,  0.73178819,  0.10660976],
       [ 0.19867461,  0.14273943,  0.01771897]])
	   
foldl(lambda a, b: a + b,x) # Okay


x = np.random.rand(3, 2).astype(np.float32)

foldl(lambda a, b: a + b,x) # fold_left:: primitive_argument_type does not hold a numeric value 
		            # type (type held: 'phylanx::execution_tree::primitive'): HPX(bad_parameter)
```
```pytb
Traceback (most recent call last):
  File "test50.py", line 17, in <module>
    foldl_eager(lambda a, b: a + b,x)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\transducer.py", line 132, in __call__
    result = self.backend.call(map(self.map_decorated, args))
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 518, in call
    return self.lazy(args).eval()
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 458, in eval
    *self.args)
RuntimeError: test50.py(6, 8): fold_left:: primitive_argument_type does not hold a numeric value type (type held: 'phylanx::execution_tree::primitive'): HPX(bad_parameter)
```

**Comment by hkaiser** [comment]
@taless474 The code snippet above works for me on  master. Could you please try again?

**Comment by taless474** [comment]
This works now, thanks.
