### ISSUE TITLE
`fmap` does not accept NumPy arrays

### ISSUE THREAD

**Issue by taless474** [STEllAR-GROUP/phylanx#941]
Having:
```py
import numpy as np
from phylanx import Phylanx

@Phylanx
def map_fn(fn, elems):
	return fmap(fn, elems)
	

x = np.array([1,2,3,4])
map_fn(lambda a:a+1,x)
```
results in:
```pytb
Traceback (most recent call last):
  File "test51.py", line 64, in <module>
    print(map_fn(lambda a:a+1,x))
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\transducer.py", line 132, in __call__
    result = self.backend.call(map(self.map_decorated, args))
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 531, in call
    return self.lazy(args).eval()
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 471, in eval
    *self.args)
RuntimeError: test51.py(60, 8): fmap:: primitive_argument_type does not hold a numeric value type (type held: 'phylanx::execution_tree::primitive'): HPX(bad_parameter)
```

**Comment by hkaiser** [comment]
@taless474 The code snippet above does work for me on master. Could you please check again?

**Comment by taless474** [comment]
I don't get the error anymore. Having
```py
import numpy as np
from phylanx import Phylanx

@Phylanx
def map_fn(fn, elems):
	return fmap(fn, elems)
	

x = np.array([1,2,3,4])
map_fn(lambda a:a+1,x)
```
there is a silent conversion to double:
```pytb
[2. 3. 4. 5.]
```
If I write it as:
```py
import numpy as np
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)

def variable(value, dtype=None, name=None, constraint=None):
	if dtype is None:
		dtype = "float32"
	if constraint is not None:
		raise TypeError("Constraint is the projection function to be "
						"applied to the variable after an optimizer update")
	from phylanx.ast.physl import PhySL
	if isinstance(value, PhySL.eval_wrapper):
		return execution_tree.variable(value.code(), dtype)
	if isinstance(value, execution_tree.variable):
		return value
	return execution_tree.variable(value, dtype=dtype, name=name)
	
def eval(func):
    return func.eval()

@Phylanx
def map_fn_eager(fn, elems):
	return fmap(fn, elems)
	
def map_fn(fn, elems, dtype):
	return variable(map_fn_eager(fn, elems),dtype=dtype)
	

x = np.array([1,2,3,4])
print(eval(map_fn(lambda a:a+1,x,"int64")))
```
I still get:
```pytb
[2. 3. 4. 5.]
```

**Comment by hkaiser** [comment]
@taless474 Yes, there was a problem with fmap always converting things to double. This however should have been fixed on master earlier today.

**Comment by taless474** [comment]
@hkaiser it works now, thanks.
