### ISSUE TITLE
Type error using `in_top_k`

### ISSUE THREAD

**Issue by taless474** [STEllAR-GROUP/phylanx#968]
@rtohid, can you please take a look at this?
```py
import numpy as np
from phylanx import Phylanx, PhylanxSession

PhylanxSession.init(1)

from phylanx.plugins.keras import in_top_k

@Phylanx
def in_top_k_eager(predictions, targets, k):
	return in_top_k(predictions, targets, k)

def in_top_k(predictions, targets, k):
	return in_top_k_eager(predictions, targets, k)
	
in_top_k([1,2],[1,0],1)
```
results in:
```pytb
Traceback (most recent call last):
  File "test63.py", line 35, in <module>
    in_top_k([1,2],[1,0],1)
  File "test63.py", line 32, in in_top_k
    return in_top_k_eager(predictions, targets, k)
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\transducer.py", line 145, in __call__
    result = self.backend.call(map(self.map_decorated, args))
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 535, in call
    return self.lazy(args).eval()
  File "C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\ast\physl.py", line 475, in eval
    *self.args)
RuntimeError: C:\Repos\phylanx\cmake-build-debug\python\build\lib.win-amd64-3.6\phylanx\plugins\keras.py(12, 23): __minus:: primitive_argument_type does not hold a numeric value type (type held: 'phylanx::ir::range'): HPX(bad_parameter)
```
We like to be able to use `in_top_k` in something like this:
```py
import numpy as np
from phylanx import Phylanx, PhylanxSession, execution_tree

PhylanxSession.init(1)

from phylanx.plugins.keras import in_top_k

def variable(value, dtype=None, name=None, constraint=None):
	if dtype is None:
		dtype = "float32"
	elif dtype not in ["float16","float32","float64","int16","int32","int64","bool"]:
		raise TypeError("unsupported dtype")
	if constraint is not None:
		raise TypeError("Constraint is the projection function to be "
						"applied to the variable after an optimizer update")
	from phylanx.ast.physl import PhySL
	if isinstance(value, PhySL.eval_wrapper):
		return execution_tree.variable(value.code(), dtype)
	if isinstance(value, execution_tree.variable):
		return value
	return execution_tree.variable(value, dtype=dtype, name=name)
	
def eval(func):
    return func.eval()


@Phylanx
def in_top_k_eager(predictions, targets, k):
	return in_top_k(predictions, targets, k)

def in_top_k(predictions, targets, k):
	return in_top_k_eager.lazy(predictions, targets, k)
	
eval(in_top_k(variable([1,2,3]),variable([1,0,3]),1))
```

**Comment by rtohid** [comment]
@taless474 for the first case, could you please try the same code with NumPy arrays as inputs?

What is the issue with the second example?

**Comment by taless474** [comment]
This is what happens when I tried it with np.arrays
![1](https://user-images.githubusercontent.com/20496946/56818923-5405ae00-680e-11e9-8e18-6e6a17846997.png)
It produces the same issue with the second example.

**Comment by rtohid** [comment]
Are you sure your input is valid? The following also doesn't work (the reference implementation provided [here](https://github.com/STEllAR-GROUP/phylanx/issues/857#issuecomment-472057320)):

```py
import numpy as np


def np_in_top_k(predictions, targets, k):
    top_k = np.argsort(-predictions)[:, :k]
    targets = targets.reshape(-1, 1)
    return np.any(targets == top_k, axis=-1)


np_in_top_k(np.array([1, 2]), np.array([1, 0]), 1)
```
output:
```
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    np_in_top_k(np.array([1, 2]), np.array([1, 0]), 1)
  File "test.py", line 5, in np_in_top_k
    top_k = np.argsort(-predictions)[:, :k]
IndexError: too many indices for array
```

**Comment by taless474** [comment]
That's a good point. I didn't account for the floor division.

**Comment by hkaiser** [comment]
@rtohid Could we change that assertion above into an exception?

**Comment by rtohid** [comment]
Are you asserting that the object is actually 1 dimensional?
